### PR TITLE
Release 1.3.0

### PR DESCRIPTION
**Pull request by olof-nord**
* Update axolotl version to 1.3.0
* Update Electron to 18.0.1
* re-generate axolotl, axolotl-web and crayfish sources
* Update flatpak-builder-tools git submodule

### CODE REVIEW

**Comment by olof-nord** [comment]
bot, build

**Comment by kkofler** [comment]
Any progress on this? The 1.2.0 Flatpak does not work at all on my PinePhone:
* Electron does not come up, it crashes somewhere.
* While I can bring it up in server mode and connect to it with Angelfish, registration then does not work. (I get to fill in the CAPTCHA, and then it just gets stuck and does not proceed. Retrying the registration then sends me straight to the PIN prompt, but the SMS with the PIN has never arrived.)

and hence I would like to try out 1.3.0. (And there is no native package for Manjaro ARM, so the Flatpak is the only supported option.)

**Comment by olof-nord** [comment]
Hello @kkofler,

In theory the release was an easy one, but the axolotl frontend got a new dependency which was using a direct git repository as a source - this didnt work with the Flathub Node tooling. I know nanu-c has done some work to fix this recently, but on my side as I am on holiday I haven't given Axolotl as much time.

The exact issue with the npm dependency is that the Flathub Node tooling unfortunately only supports a subset of the native npm dependency references. https+ssh or git@ etc. I have had a look into the python source code as to understand it better, its written in the top section in one of the main files.

The main difficulty is effectively how long a flathub build takes, with an average time probably closer to 30 minutes, this makes each iteration drag on.

**Comment by olof-nord** [comment]
See this issue for all details:
https://github.com/nanu-c/axolotl/issues/838

**Comment by olof-nord** [comment]
The CAPTCHA issue you're describing was one of the issues solved with the 1.3.0 release, in this case its the packaging which is left to do.

**Comment by olof-nord** [comment]
If you're comfortable building your own Flatpak build on your own, there is a "dev" Flatpak manifest set up in the axolotl repo, in the doc which also is in the axolotl repo you'll find info how to do it. From my experience doing it in a PinePhone it does take a very long time though.

**Comment by kkofler** [comment]
Upstream has now released 1.3.1 with the fix for Flatpak builds, when can we expect an update in Flathub?

**Comment by olof-nord** [comment]
Returning from holiday, I believe once we have https://github.com/nanu-c/axolotl/pull/874 merged, I can move on with a new Flathub release. Note that this PR is superseded by the 1.5.0 release in another [branch](https://github.com/flathub/org.nanuc.Axolotl/pull/8). I do suspect that will end up being release 1.5.1 due to the needed adjustments though.

**Comment by olof-nord** [comment]
Closing this PR in favour of the 1.5.1 release.

**Pull request closed without merging**
